run:
  timeout: '5m'
  skip-dirs:
    - 'assets'
  allow-parallel-runners: true
  modules-download-mode: 'readonly'

linters:
  enable:
    - 'asciicheck'
    - 'bodyclose'
    - 'deadcode'
    - 'depguard'
    - 'dogsled'
    - 'errcheck'
    - 'errorlint'
    - 'exportloopref'
    - 'gofumpt'
    - 'goheader'
    - 'goimports'
    - 'gomodguard'
    - 'goprintffuncname'
    - 'gosec'
    - 'gosimple'
    - 'govet'
    - 'ineffassign'
    - 'makezero'
    - 'misspell'
    - 'noctx'
    - 'paralleltest'
    - 'prealloc'
    - 'predeclared'
    - 'revive'
    - 'sqlclosecheck'
    - 'staticcheck'
    - 'structcheck'
    - 'stylecheck'
    - 'typecheck'
    - 'unconvert'
    - 'unused'
    - 'varcheck'
    - 'whitespace'

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
