// Code generated by mockery v2.15.0. DO NOT EDIT.

package gotify

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockGotifyService is an autogenerated mock type for the gotifyService type
type mockGotifyService struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, subject, message
func (_m *mockGotifyService) Send(ctx context.Context, subject string, message string) error {
	ret := _m.Called(ctx, subject, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, subject, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewMockGotifyService interface {
	mock.TestingT
	Cleanup(func())
}

// newMockGotifyService creates a new instance of mockGotifyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockGotifyService(t mockConstructorTestingTnewMockGotifyService) *mockGotifyService {
	mock := &mockGotifyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
