// Code generated by mockery v2.53.3. DO NOT EDIT.

package gotify

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockGotifyService is an autogenerated mock type for the GotifyService type
type mockGotifyService struct {
	mock.Mock
}

type mockGotifyService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockGotifyService) EXPECT() *mockGotifyService_Expecter {
	return &mockGotifyService_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, subject, message
func (_m *mockGotifyService) Send(ctx context.Context, subject string, message string) error {
	ret := _m.Called(ctx, subject, message)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, subject, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockGotifyService_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type mockGotifyService_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - subject string
//   - message string
func (_e *mockGotifyService_Expecter) Send(ctx interface{}, subject interface{}, message interface{}) *mockGotifyService_Send_Call {
	return &mockGotifyService_Send_Call{Call: _e.mock.On("Send", ctx, subject, message)}
}

func (_c *mockGotifyService_Send_Call) Run(run func(ctx context.Context, subject string, message string)) *mockGotifyService_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *mockGotifyService_Send_Call) Return(_a0 error) *mockGotifyService_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockGotifyService_Send_Call) RunAndReturn(run func(context.Context, string, string) error) *mockGotifyService_Send_Call {
	_c.Call.Return(run)
	return _c
}

// newMockGotifyService creates a new instance of mockGotifyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockGotifyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockGotifyService {
	mock := &mockGotifyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
