// Code generated by mockery v2.0.4. DO NOT EDIT.

package whatsapp

import mock "github.com/stretchr/testify/mock"

// mockWhatsappClient is an autogenerated mock type for the whatsappClient type
type mockWhatsappClient struct {
	mock.Mock
}

// Send provides a mock function with given fields: msg
func (_m *mockWhatsappClient) Send(msg interface{}) (string, error) {
	ret := _m.Called(msg)

	var r0 string
	if rf, ok := ret.Get(0).(func(interface{}) string); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(msg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
