// Code generated by mockery v2.14.0. DO NOT EDIT.

package lark

import mock "github.com/stretchr/testify/mock"

// mockSender is an autogenerated mock type for the sender type
type mockSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: subject, message
func (_m *mockSender) Send(subject string, message string) error {
	ret := _m.Called(subject, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(subject, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewMockSender interface {
	mock.TestingT
	Cleanup(func())
}

// newMockSender creates a new instance of mockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockSender(t mockConstructorTestingTnewMockSender) *mockSender {
	mock := &mockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
