// Code generated by mockery v2.12.3. DO NOT EDIT.

package lark

import "github.com/stretchr/testify/mock"

// SendToer is an autogenerated mock type for the sendToer type
type SendToer struct {
	mock.Mock
}

// SendTo provides a mock function with given fields: subject, message, id, idType
func (_m *SendToer) SendTo(subject string, message string, id string, idType string) error {
	ret := _m.Called(subject, message, id, idType)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = rf(subject, message, id, idType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type NewSendToerT interface {
	mock.TestingT
	Cleanup(func())
}

// NewSendToer creates a new instance of SendToer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSendToer(t NewSendToerT) *SendToer {
	mock := &SendToer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
