// Code generated by mockery v2.44.1. DO NOT EDIT.

package mastodon

import (
	context "context"

	go_mastodon "github.com/mattn/go-mastodon"
	mock "github.com/stretchr/testify/mock"
)

// mockmastodonClient is an autogenerated mock type for the mastodonClient type
type mockmastodonClient struct {
	mock.Mock
}

type mockmastodonClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockmastodonClient) EXPECT() *mockmastodonClient_Expecter {
	return &mockmastodonClient_Expecter{mock: &_m.Mock}
}

// PostStatus provides a mock function with given fields: ctx, toot
func (_m *mockmastodonClient) PostStatus(ctx context.Context, toot *go_mastodon.Toot) (*go_mastodon.Status, error) {
	ret := _m.Called(ctx, toot)

	if len(ret) == 0 {
		panic("no return value specified for PostStatus")
	}

	var r0 *go_mastodon.Status
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *go_mastodon.Toot) (*go_mastodon.Status, error)); ok {
		return rf(ctx, toot)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *go_mastodon.Toot) *go_mastodon.Status); ok {
		r0 = rf(ctx, toot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*go_mastodon.Status)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *go_mastodon.Toot) error); ok {
		r1 = rf(ctx, toot)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockmastodonClient_PostStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostStatus'
type mockmastodonClient_PostStatus_Call struct {
	*mock.Call
}

// PostStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - toot *go_mastodon.Toot
func (_e *mockmastodonClient_Expecter) PostStatus(ctx interface{}, toot interface{}) *mockmastodonClient_PostStatus_Call {
	return &mockmastodonClient_PostStatus_Call{Call: _e.mock.On("PostStatus", ctx, toot)}
}

func (_c *mockmastodonClient_PostStatus_Call) Run(run func(ctx context.Context, toot *go_mastodon.Toot)) *mockmastodonClient_PostStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*go_mastodon.Toot))
	})
	return _c
}

func (_c *mockmastodonClient_PostStatus_Call) Return(_a0 *go_mastodon.Status, _a1 error) *mockmastodonClient_PostStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockmastodonClient_PostStatus_Call) RunAndReturn(run func(context.Context, *go_mastodon.Toot) (*go_mastodon.Status, error)) *mockmastodonClient_PostStatus_Call {
	_c.Call.Return(run)
	return _c
}

// newMockmastodonClient creates a new instance of mockmastodonClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockmastodonClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockmastodonClient {
	mock := &mockmastodonClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
