// Code generated by mockery v2.14.0. DO NOT EDIT.

package plivo

import (
	v7 "github.com/plivo/plivo-go/v7"
	mock "github.com/stretchr/testify/mock"
)

// mockPlivoMsgClient is an autogenerated mock type for the plivoMsgClient type
type mockPlivoMsgClient struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *mockPlivoMsgClient) Create(_a0 v7.MessageCreateParams) (*v7.MessageCreateResponseBody, error) {
	ret := _m.Called(_a0)

	var r0 *v7.MessageCreateResponseBody
	if rf, ok := ret.Get(0).(func(v7.MessageCreateParams) *v7.MessageCreateResponseBody); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v7.MessageCreateResponseBody)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(v7.MessageCreateParams) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewMockPlivoMsgClient interface {
	mock.TestingT
	Cleanup(func())
}

// newMockPlivoMsgClient creates a new instance of mockPlivoMsgClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockPlivoMsgClient(t mockConstructorTestingTnewMockPlivoMsgClient) *mockPlivoMsgClient {
	mock := &mockPlivoMsgClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
