// Code generated by mockery v2.15.0. DO NOT EDIT.

package discord

import mock "github.com/stretchr/testify/mock"

// mockDiscordSession is an autogenerated mock type for the discordSession type
type mockDiscordSession struct {
	mock.Mock
}

type mockConstructorTestingTnewMockDiscordSession interface {
	mock.TestingT
	Cleanup(func())
}

// newMockDiscordSession creates a new instance of mockDiscordSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockDiscordSession(t mockConstructorTestingTnewMockDiscordSession) *mockDiscordSession {
	mock := &mockDiscordSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
