// Code generated by mockery v2.34.2. DO NOT EDIT.

package zulip

import (
	http "net/http"

	gozulipbot "github.com/ifo/gozulipbot"

	mock "github.com/stretchr/testify/mock"
)

// mockZulipClient is an autogenerated mock type for the zulipClient type
type mockZulipClient struct {
	mock.Mock
}

// Message provides a mock function with given fields: _a0
func (_m *mockZulipClient) Message(_a0 gozulipbot.Message) (*http.Response, error) {
	ret := _m.Called(_a0)

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(gozulipbot.Message) (*http.Response, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(gozulipbot.Message) *http.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(gozulipbot.Message) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockZulipClient creates a new instance of mockZulipClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockZulipClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockZulipClient {
	mock := &mockZulipClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
