package twilio

import (
	"github.com/kevinburke/twilio-go"
	"github.com/stretchr/testify/mock"
	"net/url"
)

// mockTwilioClient is an autogenerated mock type for the mockTwilioClient type
type mockTwilioClient struct {
	mock.Mock
}

// SendMessage provides a mock function with given fields: from, to, body, mediaUrls
func (_m *mockTwilioClient) SendMessage(from string, to string, body string, mediaURLs []*url.URL) (*twilio.Message, error) {
	ret := _m.Called(from, to, body, nil)

	var r0 *twilio.Message
	if rf, ok := ret.Get(0).(func(string, string, string, []*url.URL) *twilio.Message); ok {
		r0 = rf(from, to, body, nil)
	} else {
		r0 = ret.Get(0).(*twilio.Message)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, []*url.URL) error); ok {
		r1 = rf(from, to, body, nil)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
